### ISSUE TITLE
Sailor Project: in search of a Lua 5.3 production server

### ISSUE THREAD

**Issue by CodelessFuture** [EvandroLG/pegasus.lua#100]
Hi. I'm Massimiliano Bertinetti and I'm helping Etienne Dalcol maintaining Sailor.

As you already know I'm on a disperate search of a way of putting in production Sailor with Lua 5.3, so that any progress on the framework can point on the last language version.

I actually use Xavante, not the version on Luarocks but the master repo. I see @daurnimator request to rewrite part of Pegasus to support Lua-http: can we join force toward the objective of a Lua 5.3 Web Server that can support Sailor needs?

**Comment by daurnimator** [comment]
All I can say is: go for it :)

Should be easy enough to get started: let me know any lua-http questions you have.
#69

**Comment by moteus** [comment]
lua-http does not work on windows and has no plans to support it.
But pegasus works on windows and I use it on this system.
I think more interested will be implement IO independent HTTP protocol
implementation.

**Comment by RyanSquared** [comment]
> and has no plans to support it.

If support is added for [cqueues](/wahern/cqueues) to run on Windows, I've no doubt that will definitely be a gateway to running lua-http on windows.
