### ISSUE TITLE
Issue reading POST data

### ISSUE THREAD

**Issue by thomasquintana** [EvandroLG/pegasus.lua#103]
When trying to read post data the result is `Read 0 bytes.` even though the content length is > 0.

Text File:
```
This is a test.
```

Curl Command:
```
$] curl -H "Content-Type:text/plain" -X POST -d "@test.txt" localhost:9090/
```

Pegasus Server:
```lua
local server = pegasus:new({port='9090'})
server:start(function (request, response)
  local headers = request:headers()
  local method = request:method()

  if method == "POST" then
    length = tonumber(headers['Content-Length'])
    print("Content-Length: " .. length)
    if length > 0 then
        data = request:receiveBody()
        print("Read " .. #data .. " bytes.")
    end
  end

  response:write(data)
end)
```

Console Output:
```
Pegasus is up on 0.0.0.0:9090
Content-Length: 15
Read 0 bytes.
```

HTTP Request:
```
POST / HTTP/1.1
Host: localhost:9090
User-Agent: curl/7.47.0
Accept: */*
Content-Type:text/plain
Content-Length: 15
Expect: 100-continue

This is a test.
```

HTTP Response:
```
Date: Wed, 23 May 2018 16:29:47 GMT
Content-Type: text/html
Content-Length: 0
```

**Comment by DarkWiiPlayer** [comment]
This was happening to me as well; I managed to fix it by increasing the timeout from it's default value of 1 to 10. I was uploading image files though, not just short strings of text, so it might be a different issue than yours.

**Comment by EvandroLG** [comment]
@thomasquintana are you still facing this issue? I just tested here and I didn't have any problem.

**Comment by Wolf-at-SO** [comment]
> 
> 
> @thomasquintana are you still facing this issue? I just tested here and I didn't have any problem.

Maybe there is not much hope to get a reply (user's last activity dates back to 1 Mar. 2019). Maybe @DarkWiiPlayer could help to reproduce or obsolete this.

**Comment by DarkWiiPlayer** [comment]
I don't remember where I originally encountered this problem and I expect the project is long gone from my disk as well, so my chances of reproducing it are as good as anybody else's.

**Comment by Wolf-at-SO** [comment]
@DarkWiiPlayer  thanks anyway
