### ISSUE TITLE
Dot in request path

### ISSUE THREAD

**Issue by marioidival** [EvandroLG/pegasus.lua#11]
I noticed the code and test, I noticed that you concatenate the filename with a point every time, why?

pegasus/request.lua L43

 
    self._path = '.' .. filename
    self._query_string = querystring
    self._method = method

**Comment by EvandroLG** [comment]
Here is the explanation, man:
https://github.com/EvandroLG/pegasus.lua/blob/master/pegasus/response.lua#L79

Did you understand?
