### ISSUE TITLE
Security: Client can cause server DoS by requesting https on http server instance

### ISSUE THREAD

**Issue by stancikcom** [EvandroLG/pegasus.lua#118]
Hi

Client request - a get via HTTPS (https://xz.xz.xz.xz:9090) on Pegasus demo application server running as (0.0.0.0:9090) is causing DoS on server - the following message is displayed on never ending cycle:
`Failed to accept connection:closed` 

Tested on Lua 5.1.5, LuaJit 2.1.0-beta3 and with Pegasus:  0.9.6-0  on ARMF and x86 Linux platforms.

Note: application is standard Pegasus demo. The bugs seems to be in inappropriate handling of exception during socket connect.

**Comment by Tieske** [comment]
I cannot reproduce this.

I started it like this:
```
cd pegasus.lua
lua example/app.lua
```

Then used httpie to make 2 requests;

* `http https://localhost:9090` failed as expected
* `http http://localhost:9090` succeeded

So the 2nd request worked, even after the first failed. So it did not hang, or go into a loop.

**Comment by Tieske** [comment]
apologies, my bad. I tested with a develop branch. Using `v0.9.6` indeed goes into a crash loop

**Comment by Tieske** [comment]
The client will, on an error, close the socket. The bug is that it will not only close the client socket, but also the server socket. So every new `accept` call on the server socket raises error `closed`.

This was fixed 4 days ago in #113.

**Comment by EvandroLG** [comment]
Awesome @Tieske
I will update the `luarocks` module tomorrow with your changes! :+1:

**Comment by EvandroLG** [comment]
@stancikcom just uploaded the latest version to `luarocks`.
Will be closing this issue now.

@Tieske thanks again, dude! 👍

**Comment by stancikcom** [comment]
Now there is an issue with `luarock` itself while installing latest version. Have I missed something?

```xxx@xxxx:~$ sudo luarocks install pegasus
Installing https://luarocks.org/pegasus-0.9.7-0.src.rock

Error: Couldn't extract archive /tmp/luarocks_pegasus-0.9.7-0-tGpPSL/pegasus.lua.git: unrecognized filename extension```

**Comment by Tieske** [comment]
I have seen that one before I think... something with the double extension.

**Comment by Tieske** [comment]
can confirm, same issue here.

**Comment by Tieske** [comment]
fix is here: https://github.com/EvandroLG/pegasus.lua/pull/121

**Comment by stancikcom** [comment]
Yes, upgrade tested on linux and works fine. @EvandroLG  and @Tieske many thanks.

ENV: 
Linux x230 5.15.0-58-generic #64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
/usr/bin/luarocks 3.8.0

```
Installing https://luarocks.org/pegasus-0.9.7-1.src.rock
pegasus 0.9.7-1 depends on lua >= 5.1 (5.1-1 provided by VM)
pegasus 0.9.7-1 depends on mimetypes >= 1.0.0-1 (1.0.0-2 installed)
pegasus 0.9.7-1 depends on luasocket >= 0.1.0-0 (3.0rc1-2 installed)
pegasus 0.9.7-1 depends on luafilesystem >= 1.6 (1.6.2-2 installed)
pegasus 0.9.7-1 depends on lzlib >= 0.4.1.53-1 (0.4.1.53-4 installed)
pegasus 0.9.7-1 is now installed in /usr/local (license: MIT <http://opensource.org/licenses/MIT>)

Checking stability of dependencies in the absence of
pegasus 0.9.6-0...

Removing pegasus 0.9.6-0...
Removal successful.```
