### ISSUE TITLE
No way of handling GET and HEAD requests with callback

### ISSUE THREAD

**Issue by aveplen** [EvandroLG/pegasus.lua#146]
Hi 👋. Please, correct me if I'm wrong, but looks like there is a value-defaulting bug.

So when you create a server, the `location` parameter is defaulted to empty string:
https://github.com/EvandroLG/pegasus.lua/blob/5adc7dfc650f6d2ba775c6dba294f0a0748de400/src/pegasus/init.lua#L13

Then `server:start(callback)` creates a handler for every new connection passing that location to new handler:
https://github.com/EvandroLG/pegasus.lua/blob/5adc7dfc650f6d2ba775c6dba294f0a0748de400/src/pegasus/init.lua#L21

Inside the `Handler:new` function there is a check if `location` is present (which is always true due to default). And if it is, then `Files` plugin is pushed on a stack:
https://github.com/EvandroLG/pegasus.lua/blob/5adc7dfc650f6d2ba775c6dba294f0a0748de400/src/pegasus/handler.lua#L13-L18

Then all GET- and HEAD-requests are basically handled via the `Files` plugin:
https://github.com/EvandroLG/pegasus.lua/blob/5adc7dfc650f6d2ba775c6dba294f0a0748de400/src/pegasus/plugins/files.lua#L53-L55

Summarizing the above, you simply cannot create an API that would handle GET- and/or HEAD-requests via callback without patching the server object with nil-location, because the `params.location` is always present. I don't really know if it's on purpose, but looks pretty weird IYAM.

Thank you!

**Comment by aveplen** [comment]
I mean simple `server.location = nil` fixes it, but it's not obvious 😐

**Comment by Tieske** [comment]
Thx for the report. I guess the location check should check for a non-empty string then, would that fix it?

**Comment by aveplen** [comment]
That would fix it indeed, but this may break some of the apps that use the library, this is a breaking change. I'm completely fine with the fix if you are fine with that.

For non-breaking maybe just disable the behaviour of pushing `Files` on to plugins stack if some additional flag is present in init params? This flag doesn't need to be permanent though, only until next major release.

The cheapest way is just adding a note to readme - this is also fine I guess. Might save a little time for new comers.

**Comment by Tieske** [comment]
checking on the code; did you actually run into this, or is this a theoretical issue from reading the code? 

Because the way I read it, is that if the file does not exist, the `files` plugin will fail, and it will fall through to the callback.

https://github.com/EvandroLG/pegasus.lua/blob/5adc7dfc650f6d2ba775c6dba294f0a0748de400/src/pegasus/plugins/files.lua#L68

If there is an error (file wasn't found), then `response:writeFile` returns `nil + err`, and hence `stop` evaluates to `false`. That return value will then ensure the callback is still executed.

**Comment by aveplen** [comment]
I really ran into this)) This is totally reproducible, here's the snippet:

```lua
local pegasus = require "pegasus"

local server = pegasus:new({ port = '9090' })

server:start(function(request, response)
    response
        :statusCode(200, "OK")
        :write('hello pegasus world!')
    return response:close()
end)
```

The result:
```
~/project » lua main.lua
Pegasus is up on 0.0.0.0:9090
Request for: GET /
```
Socket just hangs up:
<img width="953" alt="Screenshot 2024-07-29 at 17 50 05" src="https://github.com/user-attachments/assets/71016e5a-96a8-4a23-b2ac-293196a006e8">

And if you point to existing file it just dumps the content right away (might be bad for .env or something like that actually):
<img width="953" alt="Screenshot 2024-07-29 at 17 51 55" src="https://github.com/user-attachments/assets/55abd24d-1c62-409f-a67e-483248361d4c">
