### ISSUE TITLE
HTTPS

### ISSUE THREAD

**Issue by jairojair** [EvandroLG/pegasus.lua#22]
You are thinking add https support ?

**Comment by Tieske** [comment]
If the Pegasus module is split into the server part (mostly contained in the `start` method) and the handling of the client sockets (requests) itself, then it should be easy to handle any type of request. As long as the `socket` mimics the LuaSocket client socket interface.

It would be easy to use Copas as a async scheduler for example, with either http or https.

**Comment by jairojair** [comment]
@Tieske thanks to can implement example ? or module to this ?

**Comment by Tieske** [comment]
See #24 . Allows you to create your own (https) based server

**Comment by jairojair** [comment]
Thanks @Tieske !!

**Comment by EvandroLG** [comment]
It's great! ;)
