### ISSUE TITLE
Tests and Coverage

### ISSUE THREAD

**Issue by jairojair** [EvandroLG/pegasus.lua#25]
@EvandroLG @Tieske 
What you guys think about add travis CI and Coverage to repo ? example https://github.com/moteus/lua-travis-example

Thanks your great work !

**Comment by EvandroLG** [comment]
I think that it is a good idea, man!
During this week, I want to add them :)

**Comment by jairojair** [comment]
Awesome :)

**Comment by EvandroLG** [comment]
Do you recommend some coverage tool? I tried using the busted, but the output it didn't satisfy me.
