### ISSUE TITLE
local 'location' (a nil value)

### ISSUE THREAD

**Issue by jairojair** [EvandroLG/pegasus.lua#29]
```lua
local pegasus = require 'pegasus'

local server = pegasus:new('9090')

server:start(function (request, response)
  print "It's running..."
end)
```

After the first request pegasus returned this error:

```
Pegasus is up on 0.0.0.0:9090
lua: /usr/local/share/lua/5.1/pegasus/response.lua:92: attempt to concatenate local 'location' (a nil value)
stack traceback:
	/usr/local/share/lua/5.1/pegasus/response.lua:92: in function 'processes'
	/usr/local/share/lua/5.1/pegasus/handler.lua:20: in function 'processRequest'
	/usr/local/share/lua/5.1/pegasus/init.lua:23: in function 'start'
	app.lua:5: in main chunk
	[C]: ?
```

UPDATE:
Apparently handler version in pegasus repository is different from luarocks.

**Comment by EvandroLG** [comment]
First of all, sorry for the delay in responding. I'm travelling and just now I had time to see the issues.

About the problem, it's a problem with our version 0.1.6 and our solution for "location". I removed this version of luarocks, so now everything is working again. You need to run `luarocks install pegasus`.

Is it ok for you now, man?

**Comment by jairojair** [comment]
ok thanks :)
