### ISSUE TITLE
Custom Header in response 

### ISSUE THREAD

**Issue by jairojair** [EvandroLG/pegasus.lua#30]
I need write a response with customized header. Example below

```lua
 rep.headers["WWW-Authenticate"] = "Basic realm=Example"
```
It's possible ?

Thanks :)

**Comment by Tieske** [comment]
didn't test but I think you can do it in the callback.

Se example;
```lua
server:start(function (request, response)
  print "It's running..."
end)
````
The callback function gets both request and response, so if it can be done, it should be there...

**Comment by jairojair** [comment]
The responses methods are writeHead(number) and finish(string) :cry:  
I saw the code, today is static.

```lua  
local head = string.gsub(DEFAULT_HEAD, '{{ MIME_TYPE }}', mime type) 
```
to change that is necessary modify the API correct ? @EvandroLG 

Thanks @Tieske

**Comment by EvandroLG** [comment]
Hey @jairojair 
You're right, the code's static for now =/

In its next versions, Pegasus will have it, man! :+1:

**Comment by EvandroLG** [comment]
Hey @jairojair 
I would like to see the new API of Pegasus.
Now you can customize the header :)
