### ISSUE TITLE
remove addheaders()

### ISSUE THREAD

**Issue by Tieske** [EvandroLG/pegasus.lua#42]
please remove this, and update the `addheader` function to detect whether the first argument is a table, if so, add multiple headers, if a string, add a single header.

**Comment by EvandroLG** [comment]
I agree with you. Thanks, @Tieske 
Next release will update with this solution :)

**Comment by lerrua** [comment]
:+1:

**Comment by Tieske** [comment]
No longer feasible, since it has been out for too long, it would break backward compatibility. Closing this.
