### ISSUE TITLE
app.lua example doesnt work for Arch Linux version of lua zlib?

### ISSUE THREAD

**Issue by o-jasper** [EvandroLG/pegasus.lua#54]
`luajit`(doesnt seem to look for 5.3 version),(`lua5.1`, `lua5.2`) cannot find the module, `lua`(5.3) can, but then i get:

    Pegasus is up on 0.0.0.0:9090
    lua: ./src/pegasus/compress.lua:25: bad argument #1 to 'deflate' (number expected, got function)
    stack traceback:
    	[C]: in function 'zlib.deflate'
    	./src/pegasus/compress.lua:25: in function 'pegasus.compress.processBodyData'
    	./src/pegasus/handler.lua:84: in function 'pegasus.handler.processBodyData'
    	./src/pegasus/response.lua:182: in function 'pegasus.response.write'
    	./src/pegasus/response.lua:203: in function 'pegasus.response.writeFile'
    	./src/pegasus/handler.lua:121: in function 'pegasus.handler.processRequest'
    	./src/pegasus/init.lua:29: in function 'pegasus.start'
    	example/app.lua:13: in main chunk
    	[C]: in ?

That is using the Arch Linux `lua-zlib 1:0.4-4`, it links [this repo](http://github.com/brimworks/lua-zlib). So i tried using that directly, and then it works. (somewhat vaguely)Remember messing it with the pacman repo version, but i didnt use the stream version then i think. (`"finish"` returned the string?)

**Comment by EvandroLG** [comment]
I've never checked Pegasus running over LuaJit.
For while, our expectation is that Pegasus is running over lua 5.3, 5.2 and 5.1.
For this versions is it working for you?

**Comment by o-jasper** [comment]
Just lua5.3 but think it might be a matter of configuration.

Its kindah annoying how luajit and lua dont have the same idea on how to get at C libraries.
