### ISSUE TITLE
`Request:receiveBody` comparing `nil`

### ISSUE THREAD

**Issue by o-jasper** [EvandroLG/pegasus.lua#55]
I believe it is `self._content_length` which is `nil` in request.lua#L112

However, messing around with it, i can't seem to get it to actually return the body of the request properly.. Just `"Host: 0.0.0.0:9090"`. and other header information. ([this from PegasusJs](https://github.com/o-jasper/PegasusJs/blob/master/src/PegasusJs/gen_js.lua) is doing the sending)

**Comment by o-jasper** [comment]
Replaced it with this for now... Basically just "get it all"..

    function Request:receiveBody(size)
       self:headers()
       local data, _, partial = self.client:receive("*a")
       return data or partial
    end

So basically you want it to be lazy and not get the things you dont care about.

**Comment by EvandroLG** [comment]
Hi @o-jasper 
You're right, that implementation isn't good. We need to make Pegasus has better encapsulations. 
In next releases, we'll improve it, man!

**Comment by EvandroLG** [comment]
If you have some idea to improve the Pegasus code, you can always send us as PR :)
Thanks, @o-jasper

**Comment by o-jasper** [comment]
I'd probably have PR-ed but i wasnt sure this solution was good enough.

I think getting some number size of bytes rather raw.. Better to turn it into some kind of stream. For instance emulate the thing `io.open` returns.

Making headers-fetching only-when-needed could be done transparently, as long as people dont try touch the metatable.. Not sure if either is particularly worth the effort at this point... Well, i *guess* bodies could get really long. (I dont really know how well long lua strings perform)

**Comment by EvandroLG** [comment]
thanks @o-jasper!
your solution is good. I checked here and it seems to be  working well.
in the next release, I will add your solution! :+1:

**Comment by o-jasper** [comment]
Think the pull request #56 is sufficient to represent this issue.
