### ISSUE TITLE
What if something else needs its own loop

### ISSUE THREAD

**Issue by o-jasper** [EvandroLG/pegasus.lua#57]
Wanting to implement a local-server-Tox-chat, running into this. Tox basically asks for some setup and then `tox_iterate` every-some-amount-of-time, which `tox_iteration_interval` indicates.

[This branch](https://github.com/o-jasper/pegasus.lua/tree/iterate) i tried to fix it, but now i realize that one of those commands might be blocking.

Maybe multithreading is another way to go, but i am not sure whats threadsafe and what isnt. Indeed;

> A common way to run Tox (multiple or single instance) is to have one thread running a simple tox_iterate loop, sleeping for tox_iteration_interval milliseconds on each iteration.

Hmm, probably the better approach.

**Comment by o-jasper** [comment]
Yeah, that is probably the better approach, that branch might not be a good idea..

**Comment by o-jasper** [comment]
Possibly dumb question, how do you stop it?

**Comment by Tieske** [comment]
How to stop what?

Anyway; thought of creating iterators and non-blocking stuff using Lua Coroutines?

**Comment by o-jasper** [comment]
I mean't how to stop the loop `Pegasus:start` runs.

Anyway, messed around with some solutions to my issue(needing to manage both a server and tox loop) and multithreading is not cooperating, so i looped right back here.

I'm thinking that we might want to control the loop more closely. I.e. expose `pegasus.server` and `pegasus:iterate()` does ones step. I need to be able set `server:settimeout(tox:iteration_interval(), 'b')`, so the tox loop can do its thing too.
