### ISSUE TITLE
Maybe need more tests

### ISSUE THREAD

**Issue by o-jasper** [EvandroLG/pegasus.lua#58]
Generate random data, serve up with pegasus, request with `require("socket.http").request`, and then assert equality of the body, and matching of the headers.

Plus a script that tries some different lua versions we want to work. (suggest luajit and lua)

**Comment by EvandroLG** [comment]
Hi @o-jasper 

You're right, man. We need to improve our tests. For instance, handler component doesn't have any test on logic of the plugin for now.

About Lua's version, I think that travis can help us with it ;)

**Comment by moteus** [comment]
Create PR to support Windows and several Lua versions. #79
