### ISSUE TITLE
Response:write crashes on Windows

### ISSUE THREAD

**Issue by hoensr** [EvandroLG/pegasus.lua#61]
Hi, when I write `response:write('hello pegasus world!')` like in the demo example, lua.exe crashes on me.
It seems like the os.date in line 
`self:addHeader('Date', os.date('!%a, %d %b %Y %T GMT', os.time()))`
in response.lua doesn't work in Windows?

**Comment by hoensr** [comment]
It's the "%T" which crashes.
In Lua, %T is [not officially supported](http://www.lua.org/pil/22.1.html).
I have tried it in C, and [strftime](https://msdn.microsoft.com/en-us/library/fe06s4ak(v=vs.120).aspx) crashes nastily with "%T".
I have found [one link](http://m.heise.de/forum/heise-Developer/News-Kommentare/MoonScript-statt-Lua/1-2-OT-Bug-in-os-date-mit-Windows/posting-2687969/show/) about this -- sorry, not in English; basically it says that Lua should not crash upon %T. I don't know how to handle this, though.

**Comment by EvandroLG** [comment]
Hi @hoensr 
I think in our latest updates we haven't tested on Windows =/
I'll try fix it soon. Thank you ;)

**Comment by hoensr** [comment]
You're welcome! For me, I have simply removed the "addHeader" because I don't need it. :-)
BTW, thank you for the great project!

**Comment by drewcoo** [comment]
Removing addHeader didn't do it for me. Changing the %T to %X in line 168 of response.lua fixes the problem. I'm not set up for Git on my current machine but I'll try to remember to fix and submit a pull request later.
