### ISSUE TITLE
ghpages needs update

### ISSUE THREAD

**Issue by skwerlman** [EvandroLG/pegasus.lua#62]
In the API description for requests, a `querystring` method is mentioned. While this is the terminology used internally, the actual API has a method `params` which does what the page says `querystring` should do.

This is confusing, since it requires the user to comb through the source to find the method they need.

Additionally, `methods` needs to be changed to `method`

**Comment by o-jasper** [comment]
The request parts are listed as properties, they're infact all methods.

It doesn't list `receiveBody`.

**Comment by skwerlman** [comment]
The page should also list the new `ip` and `port` parameters.

**Comment by EvandroLG** [comment]
I just released a new version of Pegasus and we're using `querystring` property again instead of `params()`.
