### ISSUE TITLE
Can't install in ubuntu 14.04

### ISSUE THREAD

**Issue by Huluhu** [EvandroLG/pegasus.lua#64]
Installing https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/pegasus-0.9.1-1.src.rock...
Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/pegasus-0.9.1-1.src.rock... switching to 'build' mode

Missing dependencies for pegasus:
lzlib >= 0.4.1.53-1

Using https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lzlib-0.4.1.53-1.src.rock... switching to 'build' mode

Error: Failed installing dependency: https://raw.githubusercontent.com/rocks-moonscript-org/moonrocks-mirror/master/lzlib-0.4.1.53-1.src.rock - Could not find library file for ZLIB
  No file libz.a in /usr/lib
  No file libz.so in /usr/lib
  No file matching libz.so.* in /usr/lib
You may have to install ZLIB in your system and/or pass ZLIB_DIR or ZLIB_LIBDIR to the luarocks command.
Example: luarocks install lzlib ZLIB_DIR=/usr/local

**Comment by skwerlman** [comment]
try `sudo apt-get install zlib1g-dev`

**Comment by Huluhu** [comment]
Thank you!

**Comment by skwerlman** [comment]
happy to help

**Comment by lucien0410** [comment]
I ran 
`sudo apt-get install zlib1g-dev  `

The error is not fixed. 

Error: Could not find library file for ZLIB
  No file libz.a in /usr/lib
  No file libz.so in /usr/lib
  No file matching libz.so.* in /usr/lib
You may have to install ZLIB in your system and/or pass ZLIB_DIR or ZLIB_LIBDIR to the luarocks command.
Example: luarocks install lzlib ZLIB_DIR=/usr/local


Any clue?
