### ISSUE TITLE
Http POST Problem

### ISSUE THREAD

**Issue by Huluhu** [EvandroLG/pegasus.lua#65]
I think I have a problem. If I POST some data from client side to pegasus, i can never get response back. However, if I still use POST without upload any data, I do have a response.

Can anybody confirm it? Or I did something stupid?

**Comment by o-jasper** [comment]
PegasusJs uses POST with data, as does my userscripts that talk to it "manually". Neither seem to have issues on either latest `development` or `master` branch.

What did you do more specifically?

**Comment by Huluhu** [comment]
Ok. 	after i modify my code from `resp:write(entry.caption)` to `resp:write(entry.caption, true)    resp:close()
   resp.client:close()`

it become normal
