### ISSUE TITLE
self.firstline got nil

### ISSUE THREAD

**Issue by Huluhu** [EvandroLG/pegasus.lua#66]
/home/ubuntu/torch/install/bin/luajit: ...e/ubuntu/torch/install/share/lua/5.1/pegasus/request.lua:41: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
        [C]: in function 'match'
        ...e/ubuntu/torch/install/share/lua/5.1/pegasus/request.lua:41: in function 'parseFirstLine'
        ...e/ubuntu/torch/install/share/lua/5.1/pegasus/request.lua:75: in function 'path'
        ...e/ubuntu/torch/install/share/lua/5.1/pegasus/handler.lua:102: in function 'processRequest'
        /home/ubuntu/torch/install/share/lua/5.1/pegasus/init.lua:29: in function 'start'
        evalWeb.lua:109: in main chunk
        [C]: in function 'dofile'
        ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by EvandroLG** [comment]
I couldn't find this bug.
Can you explain when exactly it happened?

Thanks for the report ;)

**Comment by Huluhu** [comment]
I think it happens when self.firstline is nil

**Comment by Huluhu** [comment]
/home/ubuntu/torch/install/bin/luajit: ...e/ubuntu/torch/install/share/lua/5.1/pegasus/request.lua:43: bad argument #1 to 'match' (string expected, got nil)
stack traceback:
        [C]: in function 'match'
        ...e/ubuntu/torch/install/share/lua/5.1/pegasus/request.lua:43: in function 'parseFirstLine'
        ...e/ubuntu/torch/install/share/lua/5.1/pegasus/request.lua:75: in function 'path'
        ...e/ubuntu/torch/install/share/lua/5.1/pegasus/handler.lua:102: in function 'processRequest'
        /home/ubuntu/torch/install/share/lua/5.1/pegasus/init.lua:29: in function 'start'
        evalWeb.lua:109: in main chunk
        [C]: in function 'dofile'
        ...untu/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:145: in main chunk
        [C]: at 0x00406670

**Comment by Huluhu** [comment]
so I

> 
i change this

  if (self.firstLine == nil and status == 'timeout' and partial == '' or status == 'closed') then
	    return
	  end
into

  if (self.firstLine == nil or status == 'timeout' or partial == '' or status == 'closed') then
	    return
	  end

>

**Comment by EvandroLG** [comment]
It's ok now.
Thank you, man!
