### ISSUE TITLE
Build on top of lua-http?

### ISSUE THREAD

**Issue by daurnimator** [EvandroLG/pegasus.lua#69]
Not sure if this is the right place for this; let me know if I should take this somewhere else.

I'm wondering if you'd like to (re)build pegasus on top of [lua-http](https://github.com/daurnimator/lua-http).
lua-http is a library meant to allow you do perform any/all http operations; yet not meant to be a used as a server by itself.
Pegasus would provide the request/response creation/processing logic, while lua-http would replace your luasocket operations. You would instantly gain support for multitasking, TLS, HTTP2, non-blocking operations, pipe-lining and all sorts of esoteric http stuff.

**Comment by EvandroLG** [comment]
@daurnimator let keep this conversation by e-mail? My e-mail is evandrolgoncalves@gmail.com
