### ISSUE TITLE
Getting POST data makes server crash

### ISSUE THREAD

**Issue by AlexandreRio** [EvandroLG/pegasus.lua#72]
Calling `request:post()` before calling `request:headers()` makes the server crash by comparing a number to a nil value.

The bug is at line 107 in file request.lua.

**Comment by skwerlman** [comment]
Can you post the full stacktrace? There aren't any comparisons at (or near) line 107...

**Comment by moteus** [comment]
May be call request:headers() in receiveBody method?

**Comment by EvandroLG** [comment]
@AlexandreRio This issue is already fixed.

**Comment by AlexandreRio** [comment]
@EvandroLG ok cool, sorry I didn't follow the updates to close this issue once it was fixed.
