### ISSUE TITLE
Use `pegasus.file` module.

### ISSUE THREAD

**Issue by moteus** [EvandroLG/pegasus.lua#78]
Now handler use io/lfs modules directly.
If use `file` module and allows application overwrite it
(e.g. pass as argument to handler class) it will be possible
use any custom io libraries.
E.g. can checkout my implementation based on `libuv` library.
For now I have to [overwrite](https://github.com/moteus/lua-lluv-pegasus/blob/master/src/lluv/pegasus.lua#L44) `Handler:processRequest` method.

**Comment by EvandroLG** [comment]
Hi @moteus 
I tested your PR and they were breaking some tests.

Feel free to open new Pull Requests by solving those issues
